config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :imovels
  patch "imovels" => "imovels#update"
  get 'home' => 'home#index'
  root 'home#index'

end

app/models/area_comum.rb
class AreaComum < ActiveRecord::Base
  has_many :area_comums_imovels
  has_many :imovels, :through => :area_comums_imovels
end

app/models/area_comums_imovel.rb
class AreaComumsImovel < ActiveRecord::Base
  belongs_to :area_comum
  belongs_to :imovel
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  has_one :imovel
end

app/models/imovel.rb
class Imovel < ActiveRecord::Base
  belongs_to :tipo_imovel
  belongs_to :estado
  has_many :area_comums_imovels
  has_many :area_comums, :through => :area_comums_imovels
  mount_uploaders :fotos, FotoUploader

  def self.selecionarImoveis(params)
    if !params.present? || (!params[:bairro].present? && !params[:cidade].present? && !params[:estado_id].present?)
      Imovel.all
    else
     @imovels=Imovel.by_bairro(params[:bairro]).by_cidade(params[:cidade]).by_estado_id(params[:estado_id])
    end
  end

  def self.by_bairro(param)
    return where(nil) unless param.present?
    where(["lower(bairro) LIKE lower(?)", "%"+param+"%"])
  end

  def self.by_cidade(param)
    return where(nil) unless param.present?
    where(["lower(cidade) LIKE lower(?)", "%"+param+"%"])
  end

  def self.by_estado_id(param)
    return where(nil) unless param.present?
    where(["estado_id = ?", param])
  end

end

app/models/tipo_imovel.rb
class TipoImovel < ActiveRecord::Base
  has_one :imovel
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def check_session
    if !user_signed_in?
      redirect_to '/users/sign_in'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@imovels = Imovel.selecionarImoveis(params[:imovel])

	if params[:imovel].nil?
		@imovel = Imovel.new
	else
		@imovel = Imovel.new(imovel_params)
	end	
	  respond_to do |format|
	    format.html
	  end
  end
end

app/controllers/imovels_controller.rb
class ImovelsController < ApplicationController
  before_action :set_imovel, only: [:show, :edit, :update, :destroy]
  before_filter :check_session, :only=>[:new, :edit, :destroy, :update]

  # GET /imovels
  # GET /imovels.json
  def index
	@imovels = Imovel.selecionarImoveis(params[:imovel])

	if params[:imovel].nil?
		@imovel = Imovel.new
	else
		@imovel = Imovel.new(imovel_params)
	end	
	  respond_to do |format|
	    format.html
	  end
  end

  # GET /imovels/1
  # GET /imovels/1.json
  def show
  end

  # GET /imovels/new
  def new
    @imovel = Imovel.new
  end

  # GET /imovels/1/edit
  def edit
  end

  # POST /imovels
  # POST /imovels.json
  def create
    @imovel = Imovel.new(imovel_params)
    @imovel.created_by = current_user.id
    respond_to do |format|
      if @imovel.save
        format.html { redirect_to imovel_path(@imovel), notice: 'Imóvel criado com sucesso.' }
        format.json { render :show, status: :created, location: @imovel }
      else
        format.html { render :new }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imovels/1
  # PATCH/PUT /imovels/1.json
  def update
    respond_to do |format|
      if @imovel.update(imovel_params)
        format.html { redirect_to imovel_path(@imovel), notice: 'Imóvel atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @imovel }
      else
        format.html { render :edit }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imovels/1
  # DELETE /imovels/1.json
  def destroy
    @imovel.destroy
    respond_to do |format|
      format.html { redirect_to imovels_url, notice: 'Imóvel excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imovel
      @imovel = Imovel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imovel_params
      params.require(:imovel).permit(:endereco, :bairro, :cidade, :estado_id, :tipo_imovel_id, :qtd_quartos, :metragem, :vagas_auto, :valor_aluguel, :valor_venda, :valor_condominio, :descricao, :qtd_suites, :ano_construcao, fotos: [], area_comum_ids: [] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>Seja bem-vindo!</h1>
            <p>Aqui você pode procurar imóveis de sua preferência.</p>
            <p>
		<%= form_for(@imovel, :url => { :controller => "imovels" }, :html => { :method => 'GET' }) do |f| %>
		<div class="row">
		  <div class="col-lg-6">
		    <div class="input-group">
		      <%= f.text_field :bairro, :class=>"form-control", :placeholder=>"Bairro", :style=>"width:50%" %>
		      <%= f.text_field :cidade, :class=>"form-control", :placeholder=>"Cidade", :style=>"width:50%" %>
		      <span class="input-group-btn">
			<button class="btn btn-primary" type="submit">Pesquisar</button>
		      </span>
		    </div><!-- /input-group -->
		  </div><!-- /.col-lg-6 -->
		</div><!-- /.row -->
		<% end %>
            </p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Recomendações</h3>
            </div>
        </div>
        <!-- /.row -->
        <div class="row text-center">

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

        </div>

app/views/imovels/_form.html.erb
<%= form_for(@imovel, :url => { :controller => "imovels"}) do |f| %>
  <% if @imovel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@imovel.errors.count, "error") %> prohibited this imovel from being saved:</h2>

      <ul>
      <% @imovel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" id="id" name="id" value="<%= @imovel.try(:id) %>" />

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Endereço</h3>
  </div>
  <div class="panel-body">
	  <div class="form-group">
	    <%= f.label :endereco %>
	    <%= f.text_field :endereco, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :bairro %>
	    <%= f.text_field :bairro, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :cidade %>
	    <%= f.text_field :cidade, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :estado %>
	    <%= f.select :estado_id, Estado.all.map{|c| [c.nome+' - '+c.sigla, c.id]}, {:include_blank => 'Selecione'}, {:class=>"form-control"} %>
	  </div>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Características</h3>
  </div>
  <div class="panel-body">
	  <div class="form-group">
	    <%= f.label :tipo_de_imóvel %>
	    <%= f.select :tipo_imovel_id, TipoImovel.all.map{|c| [c.nome, c.id]}, {:include_blank => 'Selecione'}, {:class=>"form-control"} %>
	  </div>
	  <div class="form-group">
	    <%= f.label :quantidade_quartos %>
	    <%= f.text_field :qtd_quartos, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :quantidade_suítes %>
	    <%= f.text_field :qtd_suites, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :Área_m² %>
	    <%= f.text_field :metragem, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :vagas_de_automóvel %>
	    <%= f.text_field :vagas_auto, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :ano_de_construção %>
	    <%= f.text_field :ano_construcao, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :Áreas_comuns %>
	    <%= f.select :area_comum_ids, AreaComum.all.collect {|x| [x.nome, x.id]}, {}, :multiple => true, :class=>"form-control input-sm" %>
	  </div>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Valores</h3>
  </div>
  <div class="panel-body">
	  <div class="form-group">
	    <%= f.label :valor_de_aluguel %>
	    <%= f.text_field :valor_aluguel, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :valor_de_venda %>
	    <%= f.text_field :valor_venda, :class=>"form-control input-sm" %>
	  </div>
	  <div class="form-group">
	    <%= f.label :valor_de_condomínio %>
	    <%= f.text_field :valor_condominio, :class=>"form-control input-sm" %>
	  </div>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Descrição</h3>
  </div>
  <div class="panel-body">
	  <div class="form-group">
	    <%= f.text_area :descricao, :class=>"form-control input-sm", :rows => "5" %>
	  </div>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Fotos</h3>
  </div>
  <div class="panel-body">
     <div class="form-group">
       <%= f.label :fotos %><br>
       <%= f.file_field :fotos, :multiple => true %>
     </div>
  </div>
</div>

  <div class="actions">
    <%= f.submit :class=>"btn btn-primary", :value=>(@imovel.id.nil?) ? "Adicionar" : "Atualizar" %>
  </div>
<% end %>

app/views/imovels/edit.html.erb
<div id="inner-container" style="width:600px">
<h1>Editar Imóvel</h1>

<%= render 'form' %>

<br />
<%= link_to 'Mostrar', imovel_path(@imovel) %> |
<%= link_to 'Voltar', imovels_path %>
</div>

app/views/imovels/index.html.erb
<h1>Pesquisar Imóveis</h1>

<%= form_for(@imovel, :url => { :controller => "imovels" }, :html => { :method => 'GET', :id => "busca_imoveis" }) do |f| %>
<div class="row">
  <div class="col-lg-6">
    <div class="input-group">
      <%= f.text_field :bairro, :class=>"form-control", :placeholder=>"Bairro", :style=>"width:34%" %>
      <%= f.text_field :cidade, :class=>"form-control", :placeholder=>"Cidade", :style=>"width:33%" %>
      <%= f.select :estado_id, Estado.all.map{|c| [c.nome+' - '+c.sigla, c.id]}, {:include_blank => 'Estado'}, {:class=>"form-control", :style=>"width:33%"} %>
      <span class="input-group-btn">
	<button class="btn btn-primary" type="submit">Pesquisar</button>
      </span>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<% end %>

<br />
<table class="table table-striped">
  <thead>
    <tr>
      <th>Resultados da busca</th>
    </tr>
  </thead>
  <tbody>
    <% @imovels.each do |imovel| %>
      <tr>
        <td width="20%"><%=image_tag(imovel.fotos[0].thumb.url, style: "width:60%;min-width:100px") if !imovel.fotos[0].nil?%></td>
        <td>
	<div class="tipo-imovel-pesquisa"><%=imovel.tipo_imovel.try(:nome)%></div>

	<span class="endereco-pesquisa"><%=imovel.bairro+" - "+imovel.cidade%></span><br />

	<span class="caracteristicas-pesquisa">
	<%if(imovel.qtd_quartos.present?);%><%=imovel.qtd_quartos%> <%=(imovel.qtd_quartos>1) ? 'quartos':'quarto'%>&nbsp;<%end%>
	<%if(imovel.qtd_suites.present?);%><%=imovel.qtd_suites%> <%=(imovel.qtd_suites>1) ? 'suítes':'suíte'%>&nbsp;<%end%> 	<%if(imovel.vagas_auto.present?);%><%=imovel.vagas_auto%> <%=(imovel.vagas_auto>1) ? 'vagas':'vaga'%>&nbsp;<%end%>
        <%if(imovel.metragem.present?);%><%=imovel.metragem%> m²&nbsp;<%end%>
	</span>

        <%if(imovel.valor_venda.present?);%><br />Valor venda: <span class="valor-pesquisa">R$ <%=imovel.valor_venda%></span><%end%>
        <%if(imovel.valor_aluguel.present?);%><br />Valor aluguel: <span class="valor-pesquisa">R$ <%=imovel.valor_aluguel%></span><%end%>

	<br /><br /><%=link_to "Ver + detalhes", imovel_path(imovel), style: "font-weight:bold" %><br />
	</td>
        <%if(user_signed_in?)%><td><%= link_to 'Editar', edit_imovel_path(imovel) %></td>
        <td><%= link_to 'Excluir', imovel_path(imovel), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }%></td><%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if(user_signed_in?)%><%= link_to 'Adicionar imóvel', new_imovel_path %><%end%>

app/views/imovels/new.html.erb
<div id="inner-container" style="width:600px">
<h1>Novo Imóvel</h1>

<%= render 'form' %>

<br />
<%= link_to 'Voltar', imovels_path %>
</div>

app/views/imovels/show.html.erb
<div id="inner-container">
<h3><%=@imovel.tipo_imovel.try(:nome)%> - <%=@imovel.bairro%> - <%=@imovel.cidade%></h3>


<div class="fotorama">
	<% @imovel.fotos.try(:each) do |i| %>
	<%= image_tag(i.url) %>
	<% end %>
</div>

<div id="caracteristicas">
	<% if !@imovel.qtd_quartos.nil? && @imovel.qtd_quartos>0 %>
	<div class="box-caracteristica">
		<h5 class="valor-caracteristica"><%=@imovel.qtd_quartos%></h2>
		<h5 class="texto-caracteristica"><%=(@imovel.qtd_quartos>1) ? 'QUARTOS':'QUARTO'%></h2>
	</div>
	<% end %>
	<% if !@imovel.qtd_suites.nil? && @imovel.qtd_suites>0 %>
	<div class="box-caracteristica">
		<h5 class="valor-caracteristica"><%=@imovel.qtd_suites%></h2>
		<h5 class="texto-caracteristica"><%=(@imovel.qtd_suites>1) ? 'SUÍTES':'SUÍTE'%></h2>
	</div>
	<% end %>
	<% if !@imovel.vagas_auto.nil? && @imovel.vagas_auto>0 %>
	<div class="box-caracteristica">
		<h5 class="valor-caracteristica"><%=@imovel.vagas_auto%></h2>
		<h5 class="texto-caracteristica"><%=(@imovel.vagas_auto>1) ? 'VAGAS':'VAGA'%></h2>
	</div>
	<% end %>
	<% if !@imovel.metragem.nil? && @imovel.metragem>0 %>
	<div class="box-caracteristica">
		<h5 class="valor-caracteristica"><%=@imovel.metragem%></h2>
		<h5 class="texto-caracteristica">ÁREA (m²)</h2>
	</div>
	<% end %>
<div>

<br />

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Descrição</h3>
  </div>
  <div class="panel-body">
	<%=simple_format(@imovel.descricao)%>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Endereço</h3>
  </div>
  <div class="panel-body">
	<%=@imovel.endereco%>, <%=@imovel.bairro%>, <%=@imovel.cidade%>, <%=@imovel.estado.nome%>
  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Características</h3>
  </div>
  <div class="panel-body">
	<table class="table">
	<tr>
		<td width="40%"><b>Tipo de imóvel</b></td>
		<td><%=@imovel.tipo_imovel.try(:nome)%></td>
	</tr>
	<tr>
		<td><b>Quantidade de quartos</b></td>
		<td><%=@imovel.qtd_quartos%></td>
	</tr>
	<tr>
		<td><b>Quantidade de suítes</b></td>
		<td><%=@imovel.qtd_suites%></td>
	</tr>
	<tr>
		<td><b>Área (m²)</b></td>
		<td><%=@imovel.metragem%></td>
	</tr>
	<tr>
		<td><b>Vagas de automóvel</b></td>
		<td><%=@imovel.vagas_auto%></td>
	</tr>
	<tr>
		<td><b>Ano de construção</b></td>
		<td><%=@imovel.ano_construcao%></td>
	</tr>
	<tr>
		<td><b>Áreas comuns</b></td>
		<td>
			<%@imovel.area_comums.each do |i|%>
			  - <%=i.nome%><br />
			<%end%>	
		</td>
	</tr>
	</table>

  </div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Valores</h3>
  </div>
  <div class="panel-body">
	<table class="table">
	<tr>
		<td width="40%"><b>Valor de aluguel (R$)</b></td>
		<td><%=@imovel.valor_aluguel%></td>
	</tr>
	<tr>
		<td><b>Valor de venda (R$)</b></td>
		<td><%=@imovel.valor_venda%></td>
	</tr>
	<tr>
		<td><b>Valor do condomínio (R$)</b></td>
		<td><%=@imovel.valor_condominio%></td>
	</tr>
	</table>
  </div>
</div>

<%if(user_signed_in?)%><%= link_to 'Editar', edit_imovel_path(@imovel) %> |<%end%>
<%= link_to 'Voltar', imovels_path %>
</div>

app/views/layouts/application.html.erb
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Imobeasy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

     <!-- Custom CSS -->
    <link href="css/heroic-features.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">imobeasy</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/imovels">Imóveis</a>
                    </li>
                    <li>
                        <a href="#">Sobre</a>
                    </li>
                    <li>
                        <a href="#">Contato</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

	<div style="float:right;width:auto">
		<% if user_signed_in? %>
		  Logado como <strong><%= current_user.email %></strong>.
		  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
		  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
		  <%= link_to "Cadastrar", new_user_registration_path, :class => 'navbar-link'  %> |
		  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
		&nbsp;
	</div>    
    <!-- Page Content -->
    <div class="container">

        <!-- Page Features -->
	<%= yield %>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; imobeasy 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>